---
title: "03 - rotando"
author: "Elio Campitelli"
output:
    ioslides_presentation:
        fig_height: 5.5
        fig_width: 10.5
        smaller: yes
        widescreen: yes
        cache: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      cache = TRUE, 
                      cache.lazy = TRUE,
                      fig.path = "share/03-onda3/",
                      warning = FALSE)

knitr::opts_knit$set(unnamed.chunk.label = "fig")

library(data.table)
library(ggplot2)
library(dplyr)
library(metR) 
library(WaveletComp)
# library(patchwork)
library(circular)
library(hrbrthemes)
library(extrafont)

source("scripts/helperfun.R")
# Plot thingys

data.world <- BuildMap(res = 1, smooth = 1)
map.world <- geom_map2(data.world)
map.SH <- geom_map2(data.world[lat %b% c(-90, 20)], color = "gray20")

# options(OutDec = ",")

pres <- ReadNetCDF("DATA/srfp.mon.mean.nc")
pres.mean <- pres[, .(pres = median(pres)), by = lat]
pres.mean <- rbind(data.table(lat = 0.0, pres = Inf), 
                   pres.mean, 
                   data.table(lat = -90.0, pres = Inf))
surface <- geom_polygon(data = pres.mean, aes(y = pres), fill = "white", 
                        alpha = 1, color = "gray30", size = 0.5)
pres <- pres[, .(pres = mean(pres)), by = .(lon, lat)]

# From https://github.com/hrbrmstr/hrbrthemes/issues/18
d <- read.csv(extrafont:::fonttable_file(), stringsAsFactors = FALSE)
d[grepl("Light", d$FontName),]$FamilyName <- font_rc_light
write.csv(d,extrafont:::fonttable_file(), row.names = FALSE)
extrafont::loadfonts()

theme_elio <- theme_minimal(base_size = 11) +
   theme(
      text = element_text(family = font_rc),
         legend.position = "bottom", legend.box = "vertical",
         panel.spacing.y = unit(5, "mm"),
         panel.spacing.x = unit(5, "mm"),
         legend.spacing = unit(2, "mm"),
         plot.margin = grid::unit(rep(3, 4), "mm"),
         legend.title = element_blank(),
         legend.box.spacing = unit(3, "mm"),
         legend.margin = margin(t = -5),
         panel.grid = element_line(color = "gray50", size = 0.2, linetype = 3),
         panel.ontop = TRUE)
theme_set(theme_elio)
update_geom_defaults(metR:::GeomTextContour, list(family = font_rc))

update_geom_defaults("contour2", list(color = "black"))
update_stat_defaults("contour2", aes(linetype = factor(-sign(..level..))))

coord_quickmap <- function(..., ylim = c(-90, 20)) {
  ggplot2::coord_quickmap(ylim = ylim, ...) 
} 

geom_contour_ <- function(..., gap = 0, rotate = FALSE) {
   if (gap != 0) {
      list(geom_contour2(..., gap = gap),
           geom_text_contour(..., rotate = rotate))
   } else {
      geom_contour2(...)
   }
}

# For vertical cross-sections
coord_latlev <- function(ratio = 20, ...) coord_fixed(ratio = ratio, ...)
coord_lonlev <- function(ratio = 20*4, ...) coord_fixed(ratio = ratio, ...)

lev.breaks <- c(10, 30, 100, 200, 500, 1000)
```

```{r read-ncep}
ncep.f <- memoise::memoise(function(lat = -90:40, 
                                    lon = 0:360,
                                    time = lubridate::as_datetime(c("1979-12-01", "2015-12-01")),
                                    level = 10:1000,
                                    vars = "gh"){
   subset <- list(lat = lat, lon = lon, level = level,
                  time = time)
   n <- ReadNetCDF("DATA/hgt.mon.mean.nc", vars = c(gh = "hgt"),
                   subset = subset) %>% 
      setnames(., c("level", "time"), c("lev", "date"))
   if ("u" %in% vars) {
      n[, u := ReadNetCDF("DATA/uwnd.mon.mean.nc", out = "vector",
                          subset = subset)[[1]]] 
   }
   if ("v" %in% vars) {
      n[, v := ReadNetCDF("DATA/vwnd.mon.mean.nc", out = "vector",
                          subset = subset)[[1]]]
   }
   n[, date := as.Date(date[1]), by = date]
   return(n)
}, cache = memoise::cache_filesystem(".rcache"))
ncep <- ncep.f(level = 200)
```

---

```{r, fig.cap = "First 4 EOFs derived from the 200hPa geopotential zonal anomaly field between 30°S and 80°S with zonal wave 1 filtered out."}
region <- expand.grid(lat = c(-65, -40),
                      lev = c(100, 700))
lats.eof <- c(-80, -30)
copy(ncep[lev == 200 & lat %between% lats.eof]) %>%
   .[, gh.minus := FilterWave(gh, k = 0:1), by = .(lat, date, lev)] %>% 
   .[, gh := gh.minus*sqrt(cos(lat*pi/180))] %>%
   .[, gh := resid(.lm.fit(cbind(1, date), gh)), 
     by = .(lon, lat)] %>% 
     {
        qs.eof <<- EOF(data = ., gh ~ date | lon + lat, n = 1:10,
                       B = 1000)
        qs.eofr <<- EOF(data = ., gh ~ date | lon + lat, n = 1:10, 
                     rotate = TRUE)
      }

qs.eof <- lapply(names(qs.eof), function(x) {
   rbindlist(list(Original = qs.eof[[x]],
                  Rotated  = qs.eofr[[x]]),
             fill = TRUE, idcol = "rotation")
})
names(qs.eof) <- names(qs.eofr)

qs.eof$sdev %>% 
   ggplot(aes(as.numeric(PC), sd, color = rotation)) +
   geom_point() +
   geom_line() +
   geom_errorbar(aes(ymin = lower, ymax = upper),
                 width = 0.3) +
   scale_x_continuous("PC", 
                      breaks = 1:20, minor_breaks = NULL) +
   scale_y_continuous("sigma") +
   scale_color_brewer(palette = "Set1")
```

```{r}
qs.eof <- CutEOF(qs.eof, 1:6)
```

---

```{r}
# qs.eof <- CutEOF(qs.eof, 1:7) 
pc.labeller <- function(qs.eof) {
   with(qs.eof$sdev, setNames(paste0(PC, " - ", scales::percent(r2)),
                              PC))
}

binwidth <- 0.01
qs.eof$right[as.numeric(PC) <= 3] %>% 
ggplot(aes(lon, lat)) +
   geom_contour_fill(aes(z = gh), 
                     breaks = AnchorBreaks(0, binwidth, 0)) +
   geom_contour3(aes(z = gh),
                 breaks = AnchorBreaks(0, binwidth, 0)) +
   map.SH +
   geom_hline(yintercept = lats.eof, linetype = 2) +
   scale_s_map() +
   scale_fill_divergent(breaks = AnchorBreaks(0, binwidth, 0),
                        guide = guide_colorstrip_bottom()) +
   coord_quickmap(ylim = c(-90, -20)) +
   facet_grid(PC~rotation)
```

---

```{r}
qs.eof$right[as.numeric(PC) > 3] %>% 
ggplot(aes(lon, lat)) +
   geom_contour_fill(aes(z = gh), 
                     breaks = AnchorBreaks(0, binwidth, 0)) +
   geom_contour3(aes(z = gh),
                 breaks = AnchorBreaks(0, binwidth, 0)) +
   map.SH +
   geom_hline(yintercept = lats.eof, linetype = 2) +
   scale_s_map() +
   scale_fill_divergent(breaks = AnchorBreaks(0, binwidth, 0),
                        guide = guide_colorstrip_bottom()) +
   coord_quickmap(ylim = c(-90, -20)) +
   facet_grid(PC~rotation)
```

--- 


```{r}
qs.eof$right[, FitWave(gh, 2:4), by = .(lat, PC, rotation)]  %>%
   ggplot(aes(lat, amplitude)) +
   geom_line(aes(color = paste0("QS", k))) +
   scale_x_latitude(trans = "reverse", ticks = 15) +
   scale_y_continuous() +
   scale_color_brewer(palette = "Set1") -> g
   # coord_fixed(500) +
g + ggforce::facet_grid_paginate(PC~rotation, page = 1, ncol = 2, nrow = 3)
```

```{r}
g + ggforce::facet_grid_paginate(PC~rotation, page = 2, ncol = 2, nrow = 3)
```

---

```{r, fig.width = 10.5/2.1}
qs.eof$left %>% 
   .[qs.eof$sdev, on = c("PC", "rotation")] %>% 
   .[, .(value = mean(gh*sd)), by = .(PC, rotation, month(date))] %>%
   dcast(month + rotation ~ PC, value.var = "value") %>% 
   .[, plot(hclust(dist(.SD[, -1])),
            labels = month.abb, hang = -1,
            main = rotation), by = .(rotation)] 
```


---

```{r, fig.cap = "Linear regrssions of geopotential height (full) and geopotential height with zonal wave1 removed (no.1)"}
binwidth <- 0.5
copy(ncep[lev == 200]) %>% 
   .[, gh.1 := FilterWave(gh, 0:1), by = .(lat, lev, date)] %>%
   .[!is.na(qs.trim(date)), .(gh = mean(gh.1)), 
     by = .(lon, lat, year(date), season = qs.trim(date))] %>%
   .[, FitLm(gh, year, se = TRUE), by = .(lat, lon, season)] %>% 
   .[regressor != "mean"] %>%
   ggplot(aes(lon, lat)) +
   geom_contour_fill(aes(z = estimate), circular = "x",
                     breaks = AnchorBreaks(0, binwidth, 0)) +
   geom_contour2(aes(z = estimate), circular = "x",
                 breaks = AnchorBreaks(0, binwidth, 0))+
   stat_subset(aes(x = Jump(lon, 2),
                   y = Jump(lat, 2),   
                   subset = abs(estimate) > se*2), geom = "point", 
               size = 0.1) +
   map.SH +
   scale_s_map() +
   scale_fill_divergent() +
   coord_quickmap() +
   facet_wrap(~season, labeller = labeller(month = month.abb),
              ncol = 2) +
   labs(title = "Tendencia lineal trimestral de altura geopotential filtrada")
```


```{r}
qs.eof$left %>% 
   copy() %>% 
   .[, .(eof = mean(gh)), 
     by = .(PC, rotation, season = qs.trim(date), year(date))] %>% 
   .[!is.na(season)] %>% 
   .[, eof := eof/sd(eof), by = .(PC, rotation)] -> eof.trim

ncep[lev == 200, .(gh = mean(gh)), 
     by = .(lon, lat, year(date), 
            season = qs.trim(date))] %>% 
   .[!is.na(season)] %>% 
   .[, gh := Anomaly(gh), by = .(lon, lat, season)] -> gh.trim 

gh.regr <- gh.trim[eof.trim, on = c("season", "year"), 
                    allow.cartesian = TRUE] %>% 
   .[, FitLm(gh, eof, se = TRUE), 
                    by = .(lon, lat, season, PC, rotation)] %>% 
   .[regressor != "mean"]
```

```{r, fig.cap = "regresión con gh"}
gh.regr %>% 
   .[, estimate.s := estimate/sd(estimate), by = .(rotation, PC)] %>% 
   ggplot( aes(lon, lat)) +
   # geom_contour2(aes(z = -value, linetype = factor(-sign(..level..))),
   # breaks = AnchorBreaks(0, 0.15, 0), color = "black") +
   geom_contour_fill(aes(z = estimate.s), circular = "x",
                     breaks = AnchorBreaks(0, 1, 0)) +
   geom_contour3(aes(z = estimate.s), circular = "x",
                 breaks = AnchorBreaks(0, 1, 0)) +
   map.SH +
   scale_fill_divergent(breaks = AnchorBreaks(0, 1, 0),
                        guide = guide_colorstrip_bottom()) +
   scale_s_map() +
   coord_quickmap() -> g
g + ggforce::facet_grid_paginate(PC + rotation~season, ncol = 4, nrow = 4, page = 1)
```

---

```{r, fig.cap = "regresión con gh"}
g + ggforce::facet_grid_paginate(PC + rotation~season, ncol = 4, nrow = 4, page = 2)
```

---

```{r, fig.cap = "regresión con gh"}
g + ggforce::facet_grid_paginate(PC + rotation~season, ncol = 4, nrow = 4, page = 3)
```

---

```{r read-sst}
sst <- ReadNetCDF("DATA/sst.nc", vars = "sst")
setnames(sst, "time", "date")
sst[, date := as.Date(date[1]), by = date]
sst <- sst[!is.na(sst)]

sst <- sst[!is.na(qs.trim(date)), 
                .(sst = mean(sst)),
                by = .(lon, lat, year(date), season = qs.trim(date))]

qs.eof$left %>%
   .[!is.na(qs.trim(date)), 
     .(gh = mean(gh)), 
     by = .(year(date), season = qs.trim(date), PC, rotation)] %>% 
   .[, gh := gh/sd(gh), by = .(PC, rotation)] %>% 
   dcast(year + season + rotation ~ PC, value.var = "gh") %>%
   .[sst, on = c("year", "season"), allow.cartesian = TRUE] %>%
   .[!is.na(PC1) & !is.na(sst)] -> sst

sst <- sst[, sst.a := Anomaly(sst), by = .(lon, lat, season)]
```

```{r calc-sst.regr}
sst[, 
    FitLm(sst.a, PC1, PC2, se = TRUE),
    by = .(lon, lat, season, rotation)] %>% 
   .[regressor != "mean"] -> sst.regr
```

```{r, fig.cap = "Regression of standarized PC with SST."}
ggplot(sst.regr, aes(lon, lat)) +
   geom_raster(aes(fill = estimate)) +
   geom_contour3(aes(z = sign(estimate)*as.numeric(abs(estimate) > se*1.6)),
                 breaks = c(-0.5, 0.5), circular = "x") +
   stat_subset(aes(subset =  abs(estimate) > se*1.6), geom = "point",
               alpha = 0.5, color = "black", size = 0.05,
               data = sst.regr[lon %in% JumpBy(unique(lon), 4) &
                                  lat %in% JumpBy(unique(lat), 4)]) +
   map.SH +
   scale_fill_divergent(guide = guide_colorstrip_bottom(),
                        breaks = AnchorBreaks(0, 0.1)) +
   scale_s_map() +
   coord_quickmap() +
   facet_grid(regressor + rotation ~ season)
```