---
title: ""
author: "Elio Campitelli"
output: 
   pdf_document:
   latex_engine: xelatex
urlcolor: blue
header_includes:
   - \usepackage[utf8]{inputenc}
---

```{r setup, include=FALSE}
# Notification
start.time <- unclass(Sys.time())
min.time <- 10
knit_doc <- knitr::knit_hooks$get("document")


knitr::knit_hooks$set(document = function(x) {
   took <- unclass(Sys.time()) - start.time
   if (unclass(Sys.time()) - start.time >= min.time) {
      notify("Done knitting!", 
             paste0("Took ", round(took), " seconds"),
             time = 5)
   }  
   knit_doc(x)
})

name <- tools::file_path_sans_ext(knitr::current_input())
knitr::opts_chunk$set(echo = FALSE,
                      cache = TRUE,
                      cache.extra = 41, 
                      warning = FALSE, message = FALSE,
                      out.extra = "",
                      cache.path = paste0("cache/", name, "/"),
                      fig.path = paste0("fig/", name, "/"),
                      fig.align = "center")

# knitr::opts_chunk$set(fig.width = 13, 
#                       fig.height = 7)

library(metR)
library(data.table)
library(ggplot2)
library(magrittr)
library(patchwork)
library(here)

here <- here::here

lev.breaks <- c(1000, 500, 300, 200, 100, 50, 10)

theme_elio <- theme_minimal(base_size = 11) +
   theme(strip.background = element_rect(fill = "#fafafa", color = NA),
         # text = element_text(family = font_rc),
         legend.position = "bottom", legend.box = "vertical",
         panel.spacing.y = unit(5, "mm"),
         panel.spacing.x = unit(5, "mm"),
         legend.spacing = unit(2, "mm"),
         plot.margin = grid::unit(rep(3, 4), "mm"),
         legend.title = element_blank(),
         legend.box.spacing = unit(3, "mm"),
         legend.margin = margin(t = -5),
         panel.grid = element_line(color = "gray50", size = 0.2, linetype = 3),
         panel.ontop = TRUE)
theme_set(theme_elio)
# theme_set(hrbrthemes::theme_ipsum_rc() + theme(panel.ontop = TRUE))

guide_colorstrip_bottom <- function(width = 25, height = 0.5, ...) {
   guide_colorstrip(title.position = "top", title.hjust = 0.5,
                    barheight = height,
                    barwidth = width, ...)
}


subset_data <- list(lat = c(-90, 0), 
                    time = lubridate::as_datetime(c("1985-01-01",
                                                    "2014-12-01")))
breaks_zero <- AnchorBreaks(0, NULL, 0)



makeActiveBinding(".", function(value) .Last.value, .GlobalEnv)

setnames <- function(x, ...) {
   names <- c(...)
   # print(names)
   data.table::setnames(x, names(names), unname(names))
}

ReIm <- function(complex) {
   list(R = Re(complex), I = Im(complex))
}

Pvaluate <- function(estimate, std.error, df, adjustement = "none") {
   p.adjust(2*pt(abs(estimate)/std.error, df, lower.tail = FALSE), method = "fdr")
}

source(here::here("scripts", "facet_nested.R"))
source(here::here("scripts", "helperfun.R"))


map_simple <- function(wrap = c(0, 360), out = "sf") {
   map <- maps::map("world", fill = TRUE, 
                    col = "transparent", plot = FALSE, wrap = c(0, 360))
   IDs <- vapply(strsplit(map$names, ":"), function(x) x[1], 
                 "")
   proj <- sp::CRS("+proj=longlat +datum=WGS84")
   map <- maptools::map2SpatialPolygons(map, IDs = IDs, 
                                        proj4string = proj)
   
   simple <- rmapshaper::ms_simplify(map, keep = 0.015)
   simple
}

map_data <- subset(fortify(map_simple()), lat <= 0)

map <- function(subset, color = "black", size = 0.2, fill = NA, ...) {
   data <- fortify(map_simple())
   subset <- eval(substitute(subset), envir = data)
   
   geom_polygon(data = data[subset, ], 
                aes(long, lat, group = group), 
                color = color, 
                size = size, 
                fill = fill,
                ...)
}

sep_ReIm <- function(dt, col, longer = TRUE) {
   names <- c("R", "I")
   expr <- quote(copy(dt)[, (names) := ReIm(col)])
   expr  <-  do.call(substitute, list(expr, 
                                      list(col = substitute(col))))
   data <- eval(expr)
   
   if (isTRUE(longer)) {
      data[, deparse(substitute(col)) := NULL]
      data <- setDT(tidyr::pivot_longer(data, R:I, names_to = "part", values_to = deparse(substitute(col))))
   }
   
   return(data[])
}

```

# Análisis con un miembro cada uno 

```{r}
subset <- list(lat = -90:0, 
               ensemble = 1,
               plev = list(50*10, 200*10))



files <- c(IPSL = "DATA/zg_Amon_IPSL-CM6A-LR_historical_i1p1f1_gr_185001-201412.nc4", 
           MRI = "DATA/zg_Amon_MRI-ESM2-0_historical_i1p1f1_gn_185001-201412.nc4")

files <- list.files("DATA", pattern = "zg_Amon", full.names = TRUE)

file <- files[1]
library(reticulate)
py_install("netcdf4")
xr <- import("xarray")


dt <- xr$
   open_dataset(file)$
   sel(plev = c(50*10, 200*10))

```


```{r read-data}

dataset <- unglue::unglue_data(files, "DATA/zg_Amon_{dataset}_{dummy}")
names(files) <- dataset$dataset

make_ceof <- function(file, lats_eof = c(-80, -20)) {
   ceof <- ReadNetCDF(file, subset = list(lat = lats_eof), vars = c(hgt = "zg")) %>% 
      setnames(plev = "lev") %>% 
      .[, lev := lev/10] %>% 
      .[, season := season(time)] %>% 
      .[, year := year(time)] %>% 
      .[, hgt_m := mean(hgt), by = .(lat, lev, season, year)] %>% 
      .[, hgt_z := hgt - hgt_m] %>% 
      .[, hgt := Anomaly(hgt_z), by = .(lon, lat, season, lev)] %>% 
      .[, hgt := hgt*sqrt(cos(lat*pi/180)), by = .(season, lev)] %>%
      .[, hgt.cpx := spectral::analyticFunction(hgt),
        by = .(lat, season, year, lev)] %>% 
      .[, hgt := hgt.cpx] %>%
      .[, list(ceof = list(EOF(hgt ~ year | lon + lat + lev, n = 1:2, suffix = "cPC"))),
        by = .(season)] %>% 
      .[]
   
   gc()
   return(ceof)
}


ceof <- lapply(files, make_ceof) %>% 
   rbindlist(idcol = "dataset")

modern <- c(1979, 2018)
# Surface mask
pres <- ReadNetCDF(here("DATA", "NCEP Reanalysis", "pres.mon.mean.nc"), 
                   subset = list(lat = -90:0))
pres.mean <- pres[, .(pres = median(pres)), by = lat]
pres.mean <- rbind(data.table(lat = 0.0, pres = Inf), 
                   pres.mean, 
                   data.table(lat = -90.0, pres = Inf))

censor_ground <- function(df, col = "underground") {
   df[, c(col) := lev > pres.mean[lat == .BY$lat, pres] , by = lat][]
}

surface <- function(lats = c(-90:0)) {
   geom_polygon(data = pres.mean[lat %between% range(lats)], aes(y = pres), fill = "white", 
                alpha = 0.9, color = "gray10", size = 0.5)
}
```


```{r, fig.cap = "Patrones espaciales del EOF complejo. Valor absoluto en sombreado, parte real en linea negra y parte imaginaria en linea azul. (dataset = ERA Interim)", fig.width=9, fig.height=11}
spatial_eof <- function(model) {
   gdata <- ceof[, ceof[[1]]$right, by = .(dataset, season)] %>% 
      .[dataset %like% model] 
   
   gdata %>%    
      ggplot(aes(lon, lat)) +
      # geom_contour_fill(aes(z = abs(hgt))) +
      geom_raster(aes(fill = abs(hgt))) +
      map(lat < 0) +
      # geom_contour2(aes(z = Im(hgt), linetype = factor(-sign(..level..))), size = 0.2) +
      geom_contour2(data = sep_ReIm(gdata, hgt), breaks = AnchorBreaks(0, exclude = 0),
                    aes(z = hgt, linetype = factor(-sign(..level..)), color = part), size = 0.2) +
      scale_fill_distiller(palette = "Oranges", direction = 1) +
      scale_x_longitude() +
      scale_y_latitude() +
      scale_color_manual(values = c(R = "black", I = "blue"), guide = "none") +
      facet_nested(season + lev ~  dataset + cPC,
                   labeller = labeller(lev = AddSuffix(" hPa"))) +
      coord_quickmap()   
}
models <- unique(ceof$dataset)
lapply(models, spatial_eof)
```