---
title: "Capítulo 3"
author: "Elio Campitelli"
output: 
   # pdf_document:
   #    latex_engine: xelatex
   powerpoint_presentation:
    # ioslides_presentation:
        fig_height: 7.6
        fig_width: 12.8
        reference_doc: template.pptx
urlcolor: blue
header_includes:
   - \usepackage[utf8]{inputenc}
params:
   season: "DJF"
   data: "data"
   psi: "psi"
---


```{r setup, include=FALSE}
# Notification

knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

library(metR)
library(data.table)
library(ggplot2)
library(magrittr)
library(patchwork)
library(here)
library(ggh4x)
library(glue)
here <- here::here


source(here("scripts", "facet_nested.R"))
source(here("scripts", "helperfun.R"))
source(here("scripts", "data_locations.R"))
knitr_set_timer()
knitr_set_cache(cache.extra  = list(params, 50))
```



```{r define-funs}
mean_season <- function(data) {
   data %>% 
      .[is.full_season(time)] %>%  
      .[, lapply(.SD, mean), by = .(lon, lat, time = seasonaly(time))]   
}


censor_ground <- function(df, col = "underground") {
   df[, c(col) := lev > pres.mean[lat == .BY$lat, pres] , by = lat][]
}

surface <- function(lats = c(-90:0)) {
   geom_polygon(data = pres.mean[lat %between% range(lats)], aes(y = pres), fill = "white", 
                alpha = 0.9, color = "gray10", size = 0.5)
}


labs_part <- c(R = "Real", I = "Imaginary", M = "Module")

divide_eof <- function(eof, which = c("left", "right", "sd")){
   setNames(lapply(which, function(x) eof[x]), which)
}

unnest_eof <- function(dt, col, which) {
   colstr <- deparse(substitute(col))
   cols <- colnames(dt)[!(colnames(dt) %in% colstr)]
   # browser()
   expr <- quote(
      dt[, col[[1]][[which]], by = c(cols)]
   )
   expr  <-  do.call(substitute, list(expr, 
                                      list(col = substitute(col))))
   eval(expr)
}

compute_ceof <- function(dt, temporal = FALSE, lats.eof = c(-80, -20), n = 1:2) {
   dt <- dt[lev %in% c(50, 200) & lat %between% lats.eof] %>%
      .[, hgt := Anomaly(hgt),
        by  = .(lat, time, lev)] 
   
   if (temporal) {
      dt <- dt[, hgt := Anomaly(hgt), by = .(lon, lat, lev)]
   }
   
   dt %>% 
      .[, hgt := hgt/sd(hgt), by = .(lev)] %>%
      .[, hgt := hgt*sqrt(cos(lat*pi/180))] %>%
      .[, hgt.cpx := spectral::analyticFunction(hgt),
        by = .(lat, time, lev)] %>% 
      .[, hgt := hgt.cpx] %>%
      EOF(hgt ~ time | lon + lat + lev, n = n, suffix = "PC", data = .)
}

plot_ceof <- function(data, eof = 1:2, formula = lev  ~  PC) {
   
   gdata <- data[, cut(ceof[[1]], eof)$right, by = .(dataset, season)]
   
   var <- data[, cut(ceof[[1]], eof)$sdev, by = .(dataset, season)] %>% 
      .[, setNames(paste0(PC, " (", scales::percent(r2), ")"), 
                   PC)]
   
   gdata %>%    
      ggperiodic::periodic(lon = c(0, 360)) %>% 
      ggplot(aes(lon, lat)) +
      geom_contour_fill(aes(z = Re(hgt)),
                        breaks = AnchorBreaks(0, 0.005, exclude = 0)) +
      geom_contour2(aes(z = Im(hgt),  linetype = factor(sign(..level..))),
                    breaks = AnchorBreaks(0, 0.005, exclude = 0)) +
      geom_map2(keep = 0.015) +
      # map(lat < 10) +
      scale_fill_divergent(guide = guide_colorstrip_bottom(35), 
                           breaks = AnchorBreaks(0, 0.005, exclude = 0),
                           limits = pm(0.039)) +
      scale_x_longitude() +
      scale_y_latitude() +
      scale_linetype_manual(values = c("1" = 1, "-1" = 2), labels = c("1" = "+", "-1" = "-"), 
                            guide = "none") +
      facet_nested(formula,
                   labeller = labeller(lev = AddSuffix(" hPa"),
                                       PC = var,
                                       dataset = labs_datasets)) +
      coord_quickmap(ylim = c(NA, -20)) +
      theme(legend.title = element_blank())
}
```


```{r read-data, cache = TRUE}
subset <- list(lat = -90:0, 
               lev = list(50, 200))


files <- c(era   = ERA5(),
           # era20 = ERA20(),
           ncep  = NCEP())

var <- c("z", "hgt")
labs_datasets <- c(era20 = "ERA20C", era = "ERA5", ncep = "NCEP")
names(var) <- files

read_nc <- function(f) {
   nc <- ReadNetCDF(f, c(hgt = unname(var[f])), subset = subset) 
   
   if (unname(var[f]) == "z") {
      nc[, hgt := hgt/9.8]
   }
   return(nc)
}

hgt <- lapply(files, read_nc) %>% 
   rbindlist(idcol = "dataset") %>% 
   .[, mean_season(.SD), by = .(dataset, lev)] %>% 
   .[season(time) == params$season]



ks <- function(vorticity_gradient, u, lat) {
   vorticity_gradient/u*(metR:::a*cos(lat*pi/180))^2
}

sqrti <- function(x) {
   sqrt(abs(x))*sign(x)
}
# 
# datos <- with_cache("datos.Rds", function() {
#    datos <- ReadNetCDF(ERA5(), vars = c(hgt = "z", "u", "v", vort = "vo", air = "t"),
#                        subset = list(lat = c(-90:10))) %>% 
#       na.omit() %>% 
#       normalise_coords() %>% 
#       .[, mean_season(.SD), by = lev]
#    
#    datos[, vort.dlat := Derivate(vort ~ lon + lat, cyclical = TRUE, sphere = TRUE)[[2]], 
#          by = .(time, lev)] %>% 
#       .[, U := mean(u), by = .(lat, lon, lev, season(time))] %>% 
#       .[, ks := sqrti(ks(vort.dlat + f.dy(lat), U, lat))] %>% 
#       .[, ":="(v_anom = Anomaly(v),
#                u_anom = Anomaly(u)),
#         by = .(lon, lat, lev, season(time))] %>%
#       .[, ":="(v_star = Anomaly(v), 
#                t_star = Anomaly(air)),
#         by = .(lat, lev, time)] %>% 
#       .[, ":="(vt_star = v_star*t_star,
#                vu = v_anom*u_anom)] %>% 
#       .[]
# })
# datos <-  datos[season(time) == params$season]

cmap <- ReadNetCDF(CMAP(), vars = c(pp = "precip"), 
                   subset = list(lat = -90:10)) %>% 
   normalise_coords() %>%
   mean_season() %>% 
   .[, pp_next := shift(pp, -1), by = .(lon, lat)] %>% 
   .[season(time) == params$season]

olr <- ReadNetCDF(OLR(), vars = "olr") %>% 
   normalise_coords() %>%
   mean_season() %>% 
   .[season(time) == params$season]


sst <- ReadNetCDF(SST()) %>% 
   # na.omit() %>% 
   normalise_coords() %>%
   .[, mean_season(.SD)] %>% 
   .[season(time) == params$season]


sfc_air <- ReadNetCDF(NCEP(vertical = "sfc"),
                      vars = "air", 
                      subset = list(lat = -90:10)) %>% 
   normalise_coords() %>%
   .[, mean_season(.SD)] %>% 
   .[season(time) == params$season]

# psi <- with_cache("psi.Rds", function() {
#     ReadNetCDF(NCEP(vertical = "sigma"),
#               subset = list(lat = c(-90, 80),
#                             lev = c(0.2101),
#                             time = c("1979-01-01", "2019-01-01"))) %>% 
#       normalise_coords() %>%
#       .[, mean_season(.SD)] %>% 
#       
#       .[, psi.z := Anomaly(psi), by = .(lat, lev, time)] %>% 
#       .[, c("f.lon", "f.lat") := WaveFlux(.SD), by = .(lev, time)] %>% 
#       .[]
# }) %>% 
#    .[season(time) == params$season]  

```

```{r calcula-ceof}
# Sacado de James

lats.eof <- c(-80, -20)

year_range <- with(hgt, common_range(time, dataset))

ceof <- hgt %>% 
   .[time %between% year_range] %>%
   .[, season := season(time)]  %>% 
   .[, list(ceof = list(compute_ceof(.SD, temporal = FALSE, n = 1:2))), by = .(dataset, season)]


# long_ceof <- datos %>% 
#    .[dataset == "era20" & season == params$season] %>% 
#    compute_ceof(temporal = FALSE)
```


# Descripción de los EOFS

---

```{r eof-espacial, fig.cap = "cEOF calculado usando la anomalía zonal. Parte real en sombreado, parte imaginaria en contornos (dataset = ERA Interim)."}
# gdata <- ceof[, ceof[[1]]$right, by = .(dataset, season)] %>% 
#    .[dataset == "era"] 
plot_ceof(ceof[season == params$season & dataset == "era"]) 
```

```{r eof-espacial_comparacion, fig.cap = "PC2 calculado usando la anomalía zonal para distintos reanálisis. Parte real en sombreado, parte imaginaria en contornos."}
plot_ceof(ceof[season == params$season], eof = 2, lev + PC ~  dataset) 
```



```{r ondas-planetarias, fig.cap = "Amplitud de las ondas zonales de cada componente principal."}
# ceof[, denormalize(ceof[[1]], "right"), by = .(dataset, season)] %>% 
ceof[, ceof[[1]]$right, by = .(dataset, season)] %>% 
   .[dataset == "era"] %>% 
   .[season == params$season] %>% 
   # .[PC == "PC2"] %>% 
   .[, FitWave(Re(hgt), 1:3), by = .(lat, lev, dataset, PC, season)] %>% 
   ggplot(aes(lat, amplitude)) +
   geom_line(aes(color = factor(k))) +
   scale_y_continuous("Amplitude", expand = expansion(mult = c(0, 0.05))) +
   scale_x_latitude(ticks = 15) +
   scale_color_brewer("Wavenumber", palette = "Set1") +
   facet_nested(lev  ~  PC, 
                labeller = labeller(lev = AddSuffix(" hPa"))) +
   coord_flip()
```


```{r eof-temporales, fig.cap = "Series temporales de eofs (era satelital)"}
ceof[, ceof[[1]]$left, by = .(dataset, season)] %>% 
   .[season == params$season] %>% 
   sep_ReIm(hgt) %>% 
   # .[, hgt := scale(hgt), by = .(PC, part, anomaly)] %>% 
   ggplot(aes(time, hgt)) +
   # geom_zero(linetype = 1) +
   geom_hline(data = function(d) d[dataset == "era", 
                                   .(x = c(mean(hgt),
                                           mean(hgt) + sd(hgt), 
                                           mean(hgt) - sd(hgt))), 
                                   by = .(PC, part, dataset)],
              aes(yintercept = x), color = "gray20") +
   geom_line(aes(color = dataset)) +
   scale_color_brewer(palette = "Set1") +
   scale_x_datetime(expand = c(0, 0)) +
   facet_nested(part ~ PC, labeller = labeller(anomaly = AddPreffix("Anomalía\n")))
```

```{r ceof-temporal-largo, fig.cap = "EOF temporal para ERA20", fig.width=18.7/2.45, fig.height=11.13/2.45}
# long_ceof$left %>% 
#    sep_ReIm(hgt) %>% 
#    .[, hgt := scale(hgt), by = .(part, PC)] %>% 
#    .[, part := forcats::fct_rev(part)] %>% 
#    ggplot(aes(time, hgt)) +
#    geom_zero(linetype = 1) +
#    geom_line() +
#    geom_smooth(span = 30/109, se = FALSE, method.args = list(degree = 1), n = 300,
#                method = "loess", color = "#FD005F") +
#    # geom_smooth(method = "lm", linetype = 2, color = "#FD005F", se = TRUE) +
#    scale_color_brewer(palette = "Set1") +
#    scale_x_continuous("Years", breaks = AnchorBreaks(1900, 20)) +
#    scale_y_continuous("") +
#    facet_nested(part ~ PC, labeller = labeller(anomaly = AddPreffix("Anomalía\n"),
#                                                part = labs_part))
```


```{r ceof-temporal-largo-regr, fig.cap = "EOF temporal para ERA20", fig.width=18.7/2.45, fig.height=11.13/2.45}

# long_ceof$left %>% 
#    sep_ReIm(hgt) %>% 
#    # .[, hgt := scale(hgt), by = .(part, PC)] %>% 
#    .[, part := forcats::fct_rev(part)] %>% 
#    # .[, hgt := scale(hgt), by = .(PC, part, anomaly)] %>% 
#    ggplot(aes(year, hgt)) +
#    geom_zero(linetype = 1) +
#    geom_line(alpha = 0.3) +
#    # geom_smooth(span = 30/109, se = FALSE, method.args = list(degree = 1), n = 300,
#    #             method = "loess", color = "#FD005F") +
#    geom_smooth(method = "lm", linetype = 1, color = "#7239b3", se = TRUE) +
#    scale_color_brewer(palette = "Set1") +
#    scale_x_continuous("Years", breaks = AnchorBreaks(1900, 20)) +
#    scale_y_continuous("") +
#    facet_nested(part ~ PC, labeller = labeller(anomaly = AddPreffix("Anomalía\n"),
#                                                part = labs_part))
```


```{r, fig.cap = "Valor absoluto de EOF temporal (ERA20C)."}
# long_ceof$left %>% 
#    copy() %>% 
#    .[, `:=`(hgt = abs(hgt), 
#             part = "M")] %>% 
#    # .[, hgt := scale(hgt), by = .(part, PC)] %>%
#    # .[, hgt := scale(hgt), by = .(PC, part, anomaly)] %>% 
#    ggplot(aes(year, hgt)) +
#    geom_zero(linetype = 1) +
#    geom_line() +
#    geom_smooth(span = 30/109, se = TRUE, method.args = list(degree = 1), n = 300,
#                method = "loess") +
#    scale_color_brewer(palette = "Set1") +
#    facet_nested(part ~ PC, labeller = labeller(anomaly = AddPreffix("Anomalía\n"),
#                                                part = labs_part))
```

```{r, fig.cap = "Fase de EOF temporal (ERA20C)."}
# long_ceof$left %>% 
#    copy() %>% 
#    .[, `:=`(hgt = Arg(hgt), 
#             part = "A")] %>% 
#    # .[, hgt := scale(hgt), by = .(part, PC)] %>%
#    # .[, hgt := scale(hgt), by = .(PC, part, anomaly)] %>% 
#    ggplot(aes(year, hgt)) +
#    geom_zero(linetype = 1) +
#    geom_line() +
#    geom_smooth(span = 30/109, se = TRUE, method.args = list(degree = 1), n = 300,
#                method = "loess") +
#    scale_color_brewer(palette = "Set1") +
#    facet_nested(part ~ PC, labeller = labeller(anomaly = AddPreffix("Anomalía\n"),
#                                                part = labs_part))
```



```{r, fig.cap = "Espectro de EOFS temporales (ERA20C)"}

# my_spectrum <- function(data, spans = NULL, R = 1000, ..., probs = 0.95) {
#    mtm <- spec.pgram(data, spans = spans, ..., plot = FALSE)
#    
#    out <- as.data.table(mtm[c("freq", "spec")])
#    
#    out[, boot_null := null_spec(data, spans = spans, R = R, ..., probs = probs)]
#    
#    return(out[])
# }
# 
# 
# 
# null_spec <- memoise::memoise(function(data, spans, R = 1000, ..., probs = 0.95) {
#    
#    b <- boot::boot(data, function(d, i) spec.pgram(d[i], spans = spans, 
#                                                    ...,
#                                                    plot = FALSE)$spec, 
#                    R = R)
#    
#    apply(b$t, 2, quantile, probs = probs)
# }
# )
# 
# long_ceof$left %>% 
#    # .[PC == "PC2"] %>% 
#    sep_ReIm(hgt) %>%
#    .[, hgt := scale(hgt), by = .(PC, part)] %>%
#    .[, my_spectrum(hgt, span = 5, R = 10000, detrend = TRUE, demean = TRUE),
#      by = .(PC, part)] %>% 
#    ggplot(aes(1/freq, spec, color = part)) +
#    geom_line() +
#    # geom_point() +
#    geom_line(aes(y = boot_null), linetype = 2) +
#    scale_x_log10("Period (years)", breaks = c(1:10, (2:10)*10), expand = c(0, 0),
#                  guide = guide_axis(check.overlap = TRUE, n.dodge = 2)) +
#    scale_y_continuous("Spectrum", expand = expansion(mult = c(0, 0.05), add = 0)) +
#    annotation_logticks(sides = "b") +
#    scale_color_brewer("Part", palette = "Set1", labels = labs_part) +
#    facet_nested( ~ PC) 
```


```{r define-regression-funs}
regress_m <- memoise::memoise(function(ceof, data, variable) {
   regr_by <- c("lon", "lat", "PC", "season")
   pval_by <- c("term", "season", "PC")
   formula <- season + term ~ PC 
   if ("lev" %in% colnames(data)) {
      regr_by <- c("lev", regr_by)
      pval_by <- c("lev", pval_by)
      formula <- season + lev + term ~ PC 
   }
   
   data <- ceof %>% 
      unnest_eof(ceof, "left") %>% 
      setnames("hgt", "EOF") %>% 
      sep_ReIm(EOF, FALSE) %>% 
      .[, ":="(R = as.numeric(scale(R)), 
               I = as.numeric(scale(I))), by = PC] %>% 
      data[., on = .NATURAL, allow.cartesian = TRUE]
   
   regr <- data %>% 
      .[, FitLm(get(variable), R, I, se = TRUE), by = c(regr_by)] %>% 
      rm_intercept() %>% 
      .[, term := factor(term, levels = c("R", "I"), labels = c("Real", "Imaginary"))] %>% 
      .[, p.val := Pvaluate(estimate, std.error, df, "fdr"), by = c(pval_by)] %>% 
      .[]
   
   class(regr) <- c("regression", class(regr))
   
   setattr(regr, "formula", formula)
   setattr(regr, "variable", variable)
   regr
})

regress <- function(ceof, data, variable) {
   # variable <- deparse(substitute(variable))
   regress_m(ceof, data, variable)
}

plot.regression <- function(x, ..., keep = 0.015, skip = 2, map.fill = NA, 
                            facet = attr(x, "formula", TRUE)) {
   lats <- range(x$lat)
   lons <- range(x$lon)
   
   ggplot(ggperiodic::periodic(x, lon = c(0, 360)), aes(lon, lat)) +
      geom_contour_fill(aes(z = estimate), ...) +
      # geom_raster(aes(fill = estimate)) +
      geom_contour2(aes(z = p.val), breaks = 0.05, size = 0.4) +
      stat_subset(aes(subset = p.val < 0.05 & if (is.na(skip)) TRUE else is.cross(lon, lat, skip = skip)),
                  size = 0.1) +
      geom_map2(keep = keep, fill = map.fill) +
      scale_fill_divergent(attr(x, "variable")) +
      scale_x_longitude() +
      scale_y_latitude() +
      coord_quickmap(xlim = lons, ylim = lats) + 
      facet_nested(facet, labeller = labeller(lev = LevLab))
}


plot_reg <- function(reg, variable = "", component = TRUE, facet = TRUE,
                     binwidth = NULL, keep = 0.015, map.fill = NA) {
   # cols <- c(c("estimate", "estiamte", "std.error", "df", "r.squared", "adj.r.squared", "p.val"),
   #           c("lon", "lat", "lev"))
   # 
   # non_cols <- setdiff(colnames(x), cols)
   
   reg$var <-  variable
   
   if (component) {
      component <- paste0(reg$PC[1], " - ", labs_part[reg$part[1]], " part")
   } else {
      component <- reg$PC[1]
   }
   
   ggperiodic::periodic(reg, lon = c(0, 360)) %>% 
      ggplot(aes(lon, lat)) +
      geom_contour_fill(aes(z = estimate), na.fill = TRUE, 
                        breaks = AnchorBreaks(0, binwidth, exclude = 0)) +
      geom_contour2(aes(z = p.val), breaks = 0.05, size = 0.2) +
      stat_subset(aes(subset = p.val <= 0.05 & is.cross(lon, lat, 1)), geom = "point", size = 0.01) +
      scale_x_longitude() +
      scale_y_latitude() +
      scale_fill_divergent(component, guide = guide_colorstrip_bottom(20),
                           labels = function(x) signif(x, 2),
                           breaks = AnchorBreaks(0, binwidth, exclude = 0)) +
      facet_nested(lev ~ var,
                   labeller = labeller(lev = AddSuffix(" hPa"))) +
      geom_map2(keep = keep, fill = map.fill) +
      coord_quickmap() 
   # theme(legend.title = element_blank())
}
```

```{r data-era-1}
era <- copy(ceof) %>% 
   .[dataset == "era" & season == params$season] 
```


# Regresiones - PC1

---

```{r}
this_pc <- "PC1"
```


```{r regressiones-1}
variables <- c("hgt", "air", "u", "v")

regressions <- variables %>% 
   lapply(regress, ceof = era, data = datos[lev %in% c(50, 100)]) %>% 
   setNames(variables) 

plot_panel <- function(this_pc, this_term) {
   lapply(regressions, function(r) {
      r %>% 
         .[PC == this_pc] %>% 
         .[term == this_term] %>% 
         plot(facet = lev~.) +
         theme(legend.position = "right")
   }) %>% 
      cowplot::plot_grid(plotlist = ., nrow = 2)   
}
```

```{r plot-panel-1-R, fig.cap = glue("Regressiones para {this_pc} y parte Real")}
plot_panel(this_pc, "Real") 
```

```{r plot-panel-1-I, fig.cap = glue("Regressiones para {this_pc} y parte Imaginaria")}
plot_panel(this_pc, "Imaginary") 
```


```{r vt1, fig.cap = glue("Producto de las regresiones con V* y con T* para {this_pc}")}
regressions$air[, estimate_star := Anomaly(estimate), by = .(lev, lat, PC, season, term)]
regressions$v[, estimate_star := Anomaly(estimate), by = .(lev, lat, PC, season, term)]

flux_regr <- regress(era, datos[lev %in% c(50, 100)], "vt_star") %>% 
   .[, estimate := regressions$air$estimate_star * regressions$v$estimate_star]

flux_regr %>% 
   .[PC == this_pc] %>% 
   ggperiodic::periodic(lon = c(0, 360)) %>% 
   ggplot(aes(lon, lat)) +
   geom_contour_fill(aes(z = estimate)) +
   # geom_raster(aes(fill = estimate)) +
   # geom_contour2(aes(z = p.val), breaks = 0.05, size = 0.4) +
   # stat_subset(aes(subset = p.val < 0.05 & if (is.na(skip)) TRUE else is.cross(lon, lat, skip = skip)),
   #             size = 0.1) +
   geom_map2() +
   scale_fill_divergent("v*t*") +
   scale_x_longitude() +
   scale_y_latitude() +
   coord_quickmap(ylim = c(NA, 0)) +
   facet_nested(lev ~ term , labeller = labeller(lev = LevLab))
```



```{r psi, fig.cap = glue("Regresión de {this_pc} con función corriente y con flujos de acción de onda.")}
psi_regr <- regress(era, psi[lat <= 30], "psi") %>% 
   .[, psi.z := estimate] %>% 
   .[, c("f.lon", "f.lat") := WaveFlux(.SD), by = .(lev, PC, season, term)]

plot_psi <- function(which_pc, binwidth) {
   skip <- 2
   ggperiodic::periodic(psi_regr, lon = c(0, 360)) %>% 
      .[PC == which_pc] %>%
      ggplot(aes(lon, lat)) +
      geom_contour_fill(aes(z = estimate/1e7), breaks = AnchorBreaks(0, binwidth, 0)) +
      # geom_raster(aes(fill = estimate)) +
      geom_contour2(aes(z = p.val), breaks = 0.05, size = 0.4) +
      stat_subset(aes(subset = p.val < 0.05 & if (is.na(skip)) TRUE else is.cross(lon, lat, skip = skip)),
                  size = 0.1) +
      geom_vector(aes(dx = f.lon, dy = f.lat,
                      x = ifelse(is.cross(lon, lat, 2), lon, NA)),
                  skip = 0, min.mag = 0, size = 0.3, arrow.angle = 12) +
      geom_map2(keep =  0.015) +
      # scale_mag(guide = "none") +
      guides(mag = "none") +
      scale_fill_divergent("psi/1e8", guide = guide_colorstrip_bottom(20),
                           breaks = AnchorBreaks(0, binwidth, 0),
                           labels = function(x) signif(x, 2)) +
      scale_x_longitude() +
      scale_y_latitude() +
      coord_quickmap(ylim = c(NA, 30)) +
      facet_grid(term ~ PC, labeller = labeller(lev = LevLab))
}
plot_psi(this_pc, binwidth = 0.05) 
```



```{r chi1, fig.cap = glue("Regresión de {this_pc} con Potencial de la velocidad")}
regress(era, psi, "chi") %>% 
   .[PC == this_pc] %>% 
   .[lat <= 30] %>% 
   plot()
```


```{r olr-sst, fig.cap = glue("Regresión de {this_pc} con OLR y con SST")}
g1 <- regress(era, olr, "olr") %>%
   .[lat <= 10] %>% 
   .[PC == this_pc] %>% 
   plot() 

g2 <- regress(era, sst, "sst") %>%
   .[lat <= 10] %>% 
   .[PC == this_pc] %>% 
   plot(na.fill = TRUE, map.fill = "white")

# g1 + g2   
cowplot::plot_grid(g1, g2)
```


```{r mei1, fig.cap = glue("EOF y MEI para {this_pc}")}
mei <- rsoi::download_mei(TRUE, file = "DATA/mei.csv") %>% 
   as.data.table() %>% 
   .[, .(time = as.POSIXct(Date), MEI = MEI)]

plot_index <- function(index, this_pc) {
   col_index <- as.name(setdiff(colnames(index), "time"))
   unnest_eof(era, ceof, "left") %>% 
      sep_ReIm(hgt) %>% 
      .[index, on = "time"] %>%
      na.omit() %>% 
      .[PC == this_pc] %>% 
      ggplot(aes({{ col_index }}, hgt, color = part)) +
      geom_point() +
      geom_smooth(method = "lm") +
      scale_y_continuous("EOF") +
      scale_color_brewer("Parte", palette = "Set1") +
      labs()
}

plot_index(mei, this_pc) 
```

```{r}
aao <- rsoi::download_aao(TRUE, file = "DATA/aao.csv") %>% 
   as.data.table() %>% 
   .[, .(time = as.POSIXct(Date), AAO = AAO)]
plot_index(aao, this_pc)
```


```{r u-mean, fig.cap = glue("Regresión de {this_pc} con U medio zonal. U climatológico en contornos")} 
mean_u <- datos %>% 
   .[, .(u = mean(u), lon = 0), by = .(lat, lev)] 
skip <- 1
datos %>% 
   .[, .(u = mean(u), lon = 0), by = .(lat, lev, time)] %>% 
   regress(era, ., "u") %>% 
   .[PC == this_pc] %>% 
   ggplot(aes(lat, lev))  +
   geom_contour_fill(aes(z = estimate)) +
   geom_contour2(aes(z = p.val), breaks = 0.05, size = 0.4) +
   stat_subset(aes(subset = p.val < 0.05 & if (is.na(skip)) TRUE else is.cross(lon, lev, skip = skip)),
               size = 0.1) +
   geom_contour2(aes(z = u), data = mean_u, color = "gray50", size = 0.6) +
   scale_x_longitude() +
   scale_y_level() +
   scale_fill_divergent("u") +
   facet_nested(season + term ~ PC)
```

```{r vortex1, fig.cap = glue("{this_pc} vs. índice del vórtice polar (U medio entre 60S y 50S en 50hPa)")}
vortex <- datos[lev == 50 & lat %between% c(-60, -50),
                .(polar_index = mean(u)), by = .(time)]
plot_index(vortex, this_pc)
```

```{r u-partes, fig.cap = glue("Regresión de U media sectorizada con {this_pc}")}
u_media_partes <- copy(datos) %>% 
   .[, franja_lon := lon %between% c(60, 300)] %>% 
   .[, .(u = mean(u)), by = .(lev, time, franja_lon, lat)]

franja_lon_lab <- c("TRUE" = "Entre 60E y 60O",
                    "FALSE" = "Resto del globo")

unnest_eof(era, ceof, "left") %>% 
   sep_ReIm(hgt, FALSE) %>% 
   .[PC == this_pc] %>% 
   .[u_media_partes, on = "time", allow.cartesian = TRUE] %>% 
   .[, FitLm(u, R, I, se = TRUE), by = .(lat, lev, franja_lon, PC)] %>% 
   rm_intercept() %>% 
   .[, term := factor(term, levels = c("R", "I"), labels = c("Real", "Imaginary"))] %>% 
   .[, p.val := Pvaluate(estimate, std.error, df, "fdr"), by = .(PC, franja_lon)] %>% 
   ggplot(aes(lat, lev))  +
   geom_contour_fill(aes(z = estimate)) +
   geom_contour2(aes(z = p.val), breaks = 0.05, size = 0.4) +
   stat_subset(aes(subset = p.val < 0.05 & is.cross(lat, lev, skip = 1)),
               size = 0.1) +
   # geom_contour2(aes(z = u), data = mean_u, color = "gray50", size = 0.6) +
   scale_x_longitude() +
   scale_y_level() +
   scale_fill_divergent("u") +
   facet_nested(term ~ franja_lon, labeller = labeller(franja_lon = franja_lon_lab))
```


# Regresiones - PC2

---

```{r}
this_pc <- "PC2"
```


```{r plot-panel-2-R, fig.cap = glue("Regressiones para {this_pc} y parte Real")}
plot_panel(this_pc, "Real")
```

```{r plot-panel-2-I, fig.cap = glue("Regressiones para {this_pc} y parte Imaginaria")}
plot_panel(this_pc, "Imaginary")
```


```{r vt2, fig.cap = glue("Producto de las regresiones con V* y con T* para {this_pc}")}
regressions$air[, estimate_star := Anomaly(estimate), by = .(lev, lat, PC, season, term)]
regressions$v[, estimate_star := Anomaly(estimate), by = .(lev, lat, PC, season, term)]

flux_regr <- regress(era, datos[lev %in% c(50, 100)], "vt_star") %>% 
   .[, estimate := regressions$air$estimate_star * regressions$v$estimate_star]

flux_regr %>% 
   .[PC == this_pc] %>% 
   ggperiodic::periodic(lon = c(0, 360)) %>% 
   ggplot(aes(lon, lat)) +
   geom_contour_fill(aes(z = estimate)) +
   # geom_raster(aes(fill = estimate)) +
   # geom_contour2(aes(z = p.val), breaks = 0.05, size = 0.4) +
   # stat_subset(aes(subset = p.val < 0.05 & if (is.na(skip)) TRUE else is.cross(lon, lat, skip = skip)),
   #             size = 0.1) +
   geom_map2() +
   scale_fill_divergent("v*t*") +
   scale_x_longitude() +
   scale_y_latitude() +
   coord_quickmap(ylim = c(NA, 0)) +
   facet_nested(lev ~ term , labeller = labeller(lev = LevLab))
```



```{r psi2, fig.cap = glue("Regresión de {this_pc} con función corriente y con flujos de acción de onda.")}
psi_regr <- regress(era, psi[lat <= 30], "psi") %>% 
   .[, psi.z := estimate] %>% 
   .[, c("f.lon", "f.lat") := WaveFlux(.SD), by = .(lev, PC, season, term)]

plot_psi <- function(which_pc, binwidth) {
   skip <- 2
   ggperiodic::periodic(psi_regr, lon = c(0, 360)) %>% 
      .[PC == which_pc] %>%
      ggplot(aes(lon, lat)) +
      geom_contour_fill(aes(z = estimate/1e7), breaks = AnchorBreaks(0, binwidth, 0)) +
      # geom_raster(aes(fill = estimate)) +
      geom_contour2(aes(z = p.val), breaks = 0.05, size = 0.4) +
      stat_subset(aes(subset = p.val < 0.05 & if (is.na(skip)) TRUE else is.cross(lon, lat, skip = skip)),
                  size = 0.1) +
      geom_vector(aes(dx = f.lon, dy = f.lat,
                      x = ifelse(is.cross(lon, lat, 2), lon, NA)),
                  skip = 0, min.mag = 0, size = 0.3, arrow.angle = 12) +
      geom_map2(keep =  0.015) +
      # scale_mag(guide = "none") +
      guides(mag = "none") +
      scale_fill_divergent("psi/1e8", guide = guide_colorstrip_bottom(20),
                           breaks = AnchorBreaks(0, binwidth, 0),
                           labels = function(x) signif(x, 2)) +
      scale_x_longitude() +
      scale_y_latitude() +
      coord_quickmap(ylim = c(NA, 30)) +
      facet_grid(term ~ PC, labeller = labeller(lev = LevLab))
}
plot_psi(this_pc, binwidth = 0.05) 
```



```{r chi2, fig.cap = glue("Regresión de {this_pc} con Potencial de la velocidad")}
regress(era, psi, "chi") %>% 
   .[PC == this_pc] %>% 
   .[lat <= 30] %>% 
   plot()
```


```{r olr-sst2, fig.cap = glue("Regresión de {this_pc} con OLR y con SST")}
g1 <- regress(era, olr, "olr") %>%
   .[lat <= 10] %>% 
   .[PC == this_pc] %>% 
   plot() 

g2 <- regress(era, sst, "sst") %>%
   .[lat <= 10] %>% 
   .[PC == this_pc] %>% 
   plot(na.fill = TRUE, map.fill = "white")

# g1 + g2   
cowplot::plot_grid(g1, g2)
```


```{r mei2, fig.cap = glue("EOF y MEI para {this_pc}")}
mei <- rsoi::download_mei(TRUE, file = "DATA/mei.csv") %>% 
   as.data.table() %>% 
   .[, .(time = as.POSIXct(Date), MEI = MEI)]

plot_index <- function(index, this_pc) {
   col_index <- as.name(setdiff(colnames(index), "time"))
   unnest_eof(era, ceof, "left") %>% 
      sep_ReIm(hgt) %>% 
      .[index, on = "time"] %>%
      na.omit() %>% 
      .[PC == this_pc] %>% 
      ggplot(aes({{ col_index }}, hgt, color = part)) +
      geom_point() +
      geom_smooth(method = "lm") +
      scale_y_continuous("EOF") +
      scale_color_brewer("Parte", palette = "Set1") 
}

plot_index(mei, this_pc)
```

```{r aao2}
aao <- rsoi::download_aao(TRUE, file = "DATA/aao.csv") %>% 
   as.data.table() %>% 
   .[, .(time = as.POSIXct(Date), AAO = AAO)]
plot_index(aao, this_pc)
```


```{r u-mean2, fig.cap = glue("Regresión de {this_pc} con U medio zonal. U climatológico en contornos")} 
mean_u <- datos %>% 
   .[, .(u = mean(u), lon = 0), by = .(lat, lev)] 
skip <- 1
datos %>% 
   .[, .(u = mean(u), lon = 0), by = .(lat, lev, time)] %>% 
   regress(era, ., "u") %>% 
   .[PC == this_pc] %>% 
   ggplot(aes(lat, lev))  +
   geom_contour_fill(aes(z = estimate)) +
   geom_contour2(aes(z = p.val), breaks = 0.05, size = 0.4) +
   stat_subset(aes(subset = p.val < 0.05 & if (is.na(skip)) TRUE else is.cross(lon, lev, skip = skip)),
               size = 0.1) +
   geom_contour2(aes(z = u), data = mean_u, color = "gray50", size = 0.6) +
   scale_x_longitude() +
   scale_y_level() +
   scale_fill_divergent("u") +
   facet_nested(season + term ~ PC)
```

```{r vortex2, fig.cap = glue("{this_pc} vs. índice del vórtice polar (U medio entre 60S y 50S en 50hPa)")}
vortex <- datos[lev == 50 & lat %between% c(-60, -50),
                .(polar_index = mean(u)), by = .(time)]
plot_index(vortex, this_pc)
```

```{r u-partes2, fig.cap = glue("Regresión de U media sectorizada con {this_pc}")}
# u_media_partes <- copy(datos) %>% 
#    .[, franja_lon := cut(lon, c(-Inf, 180, 240, 300, 360))] %>% 
#    .[, .(u = mean(u)), by = .(lev, time, franja_lon, lat)]
# 
# # franja_lon_lab <- c("TRUE" = "Entre 60E y 60O",
#                     # "FALSE" = "Resto del globo")
# 
# unnest_eof(era, ceof, "left") %>% 
#    sep_ReIm(hgt, FALSE) %>% 
#    .[PC == this_pc] %>% 
#    .[u_media_partes, on = "time", allow.cartesian = TRUE] %>% 
#    .[, FitLm(u, R, I, se = TRUE), by = .(lat, lev, franja_lon, PC)] %>% 
#    rm_intercept() %>% 
#    .[, term := factor(term, levels = c("R", "I"), labels = c("Real", "Imaginary"))] %>% 
#    .[, p.val := Pvaluate(estimate, std.error, df, "fdr"), by = .(PC, franja_lon)] %>% 
#    ggplot(aes(lat, lev))  +
#    geom_contour_fill(aes(z = estimate)) +
#    geom_contour2(aes(z = p.val), breaks = 0.05, size = 0.4) +
#    stat_subset(aes(subset = p.val < 0.05 & is.cross(lat, lev, skip = 1)),
#                size = 0.1) +
#    # geom_contour2(aes(z = u), data = mean_u, color = "gray50", size = 0.6) +
#    scale_x_longitude() +
#    scale_y_level() +
#    scale_fill_divergent("u") +
#    facet_nested(term ~ franja_lon)
```

