---
title: "Estratósfera o no?"
author: "Elio Campitelli"
output: 
   # pdf_document:
   #    latex_engine: xelatex
   powerpoint_presentation:
    # ioslides_presentation:
        fig_height: 7.6
        fig_width: 12.8
        reference_doc: template.pptx
urlcolor: blue
header_includes:
   - \usepackage[utf8]{inputenc}
---


```{r setup, include=FALSE}
# Notification
start.time <- unclass(Sys.time())
min.time <- 10
knit_doc <- knitr::knit_hooks$get("document")


knitr::knit_hooks$set(document = function(x) {
   took <- unclass(Sys.time()) - start.time
   if (unclass(Sys.time()) - start.time >= min.time) {
      notify("Done knitting!", 
             paste0("Took ", round(took), " seconds"),
             time = 5)
   }  
   knit_doc(x)
})

name <- tools::file_path_sans_ext(knitr::current_input())
knitr::opts_chunk$set(echo = FALSE,
                      cache = TRUE,
                      cache.extra = 41, 
                      warning = FALSE, message = FALSE,
                      # out.extra = "",
                      cache.path = paste0("cache/", name, "/"),
                      fig.path = paste0("fig/", name, "/")
                      # fig.align = "center"
)

# knitr::opts_chunk$set(fig.width = 13, 
#                       fig.height = 7)

library(metR)
library(data.table)
library(ggplot2)
library(magrittr)
library(patchwork)
library(here)

here <- here::here

lev.breaks <- c(1000, 500, 300, 200, 100, 50, 10)

theme_elio <- theme_minimal(base_size = 16) +
   theme(strip.background = element_rect(fill = NA, color = "gray30"),
         # text = element_text(family = font_rc),
         legend.position = "bottom", legend.box = "vertical",
         panel.spacing.y = unit(5, "mm"),
         panel.spacing.x = unit(5, "mm"),
         legend.spacing = unit(2, "mm"), 
         panel.border = element_rect(colour = "black", fill = NA),
         plot.margin = grid::unit(rep(3, 4), "mm"),
         # legend.title = element_blank(),
         legend.box.spacing = unit(3, "mm"),
         legend.margin = margin(t = -5),
         panel.grid = element_line(color = "gray10", size = 0.4, linetype = 3),
         panel.ontop = TRUE)
theme_set(theme_elio)
# theme_set(hrbrthemes::theme_ipsum_rc() + theme(panel.ontop = TRUE))

guide_colorstrip_bottom <- function(width = 25, height = 0.5, ...) {
   guide_colorstrip(title.position = "top", title.hjust = 0.5,
                    barheight = height,
                    barwidth = width, ...)
}


subset_data <- list(lat = c(-90, 0), 
                    time = lubridate::as_datetime(c("1985-01-01",
                                                    "2014-12-01")))
breaks_zero <- AnchorBreaks(0, NULL, 0)



makeActiveBinding(".", function(value) .Last.value, .GlobalEnv)

setnames <- function(x, ...) {
   names <- c(...)
   # print(names)
   data.table::setnames(x, unname(names), names(names))
}

ReIm <- function(complex) {
   list(R = Re(complex), I = Im(complex))
}

Pvaluate <- function(estimate, std.error, df, adjustement = "none") {
   p.adjust(2*pt(abs(estimate)/std.error, df, lower.tail = FALSE), method = "fdr")
}

source(here::here("scripts", "facet_nested.R"))
source(here::here("scripts", "helperfun.R"))


map_simple <- function(wrap = c(0, 360), out = "sf") {
   map <- maps::map("world", fill = TRUE, 
                    col = "transparent", plot = FALSE, wrap = wrap)
   IDs <- vapply(strsplit(map$names, ":"), function(x) x[1], 
                 "")
   proj <- sp::CRS("+proj=longlat +datum=WGS84")
   map <- maptools::map2SpatialPolygons(map, IDs = IDs, 
                                        proj4string = proj)
   
   simple <- rmapshaper::ms_simplify(map, keep = 0.015)
   simple
}

map_data <- subset(fortify(map_simple()), lat <= 0)

map <- function(subset = NULL, color = "black", size = 0.2, fill = NA, wrap = c(0, 360), ...) {
   data <- fortify(map_simple(wrap = wrap)) %>% 
      .[, c("long", "lat", "group")]
   subset <- eval(substitute(subset), envir = data)
   if (is.null(subset)) subset <- TRUE
   
   geom_polygon(data = data[subset, ], 
                aes(long, lat, group = group), 
                color = color, 
                size = size, 
                fill = fill,
                ...)
}

sep_ReIm <- function(dt, col, longer = TRUE) {
   names <- c("R", "I")
   expr <- quote(copy(dt)[, (names) := ReIm(col)])
   expr  <-  do.call(substitute, list(expr, 
                                      list(col = substitute(col))))
   data <- eval(expr)
   
   if (isTRUE(longer)) {
      data[, deparse(substitute(col)) := NULL]
      data <- setDT(tidyr::pivot_longer(data, R:I, names_to = "part", values_to = deparse(substitute(col))))
   }
   
   return(data[])
}

geom_zero <- function(dir = "h", ...) {
   switch(dir,
          h = geom_hline(yintercept = 0, ...),
          v = geom_vline(xintercept = 0, ...))
}

```



```{r define-funs}
compute_ceof <- function(dt, temporal = FALSE, lats.eof = c(-80, -20), n = 1:2) {
   # browser()
   dt <- dt[lat %between% lats.eof] %>%
      .[, hgt := Anomaly(hgt),
        by  = .(lat, year, lev)] 
   
   if (temporal) {
      dt <- dt[, hgt := Anomaly(hgt), by = .(lon, lat, lev)]
   }
   
   dt %>% 
      .[, hgt := hgt/sd(hgt), by = lev] %>%
      .[, hgt := hgt*sqrt(cos(lat*pi/180))] %>%
      .[, hgt.cpx := spectral::analyticFunction(hgt),
        by = .(lat, year, lev)] %>% 
      .[, hgt := hgt.cpx] %>%
      EOF(hgt ~ year | lon + lat + lev, n = n, suffix = "PC", data = .)
}

compute_ceof_sep <- function(dt, temporal = FALSE, lats.eof = c(-80, -20), n = 1:2) {
   # browser()
   dt <- dt[lat %between% lats.eof] %>%
      .[, hgt := Anomaly(hgt),
        by  = .(lat, year)] 
   
   if (temporal) {
      dt <- dt[, hgt := Anomaly(hgt), by = .(lon, lat)]
   }
   
   dt %>% 
      .[, hgt := hgt/sd(hgt)] %>%
      .[, hgt := hgt*sqrt(cos(lat*pi/180))] %>%
      .[, hgt.cpx := spectral::analyticFunction(hgt),
        by = .(lat, year)] %>% 
      .[, hgt := hgt.cpx] %>%
      EOF(hgt ~ year | lon + lat, n = n, suffix = "PC", data = .)
}


plot_ceof <- function(data, eof = 1:2, formula = lev  ~  PC) {
   
   gdata <- data[, cut(ceof[[1]], eof)$right, by = .(dataset, season, lev)]
   
   var <- data[, cut(ceof[[1]], eof)$sdev, by = .(dataset, season, lev)] %>% 
      .[, setNames(paste0(PC, " (", scales::percent(r2), ")"), 
                   PC)]
   
   gdata %>%    
      ggperiodic::periodic(lon = c(0, 360)) %>% 
      ggplot(aes(lon, lat)) +
      geom_contour_fill(aes(z = Re(hgt)),
                        breaks = AnchorBreaks(0, 0.005, exclude = 0)) +
      geom_contour2(aes(z = Im(hgt),  linetype = factor(sign(..level..))),
                    breaks = AnchorBreaks(0, 0.005, exclude = 0)) +
      map(lat < 10) +
      scale_fill_divergent(guide = guide_colorstrip_bottom(35), 
                           breaks = AnchorBreaks(0, 0.005, exclude = 0),
                           limits = pm(0.039)) +
      scale_x_longitude() +
      scale_y_latitude() +
      scale_linetype_manual(values = c("1" = 1, "-1" = 2), labels = c("1" = "+", "-1" = "-"), 
                            guide = "none") +
      facet_nested(formula,
                   labeller = labeller(lev = AddSuffix(" hPa"),
                                       PC = var,
                                       dataset = labs_datasets)) +
      coord_quickmap(ylim = c(NA, -20)) +
      theme(legend.title = element_blank())
}

```




```{r read-data}
subset <- list(latitude = -90:0, 
               level = list(50, 200))


files <- c(era   = here("DATA", "ERA-Interim", "erai.mon.mean.nc"),
           era20 = here("DATA", "ERA-20C", "era20c.mon.mean.nc"),
           ncep  = here("DATA", "NCEP Reanalysis", "hgt.mon.mean.nc"))
var <- c("z", "z", "hgt")
labs_datasets <- c(era20 = "ERA20C", era = "ERA-I", ncep = "NCEP")
names(var) <- files
subsets <- list(
   era = subset,
   era20 = subset,
   ncep = list(lat = -90:0,
               level = list(50, 200)))
names(subsets) <- files

read_nc <- function(f) {
   nc <- ReadNetCDF(f, c(hgt = unname(var[f])), subset = subsets[[f]]) 
   
   if (unname(var[f]) == "z") {
      nc[, hgt := hgt/9.8] %>% 
         setnames(lon = "longitude", lat = "latitude", lev = "level") %>% 
         .[]
   }
   
   if (unname(var[f]) == "hgt") {
      setnames(nc, lev = "level") %>% 
         .[]
   }
   return(nc)
}

datos <- lapply(files, read_nc) %>% 
   rbindlist(idcol = "dataset") %>% 
   .[, year := year(time[1]), by = time] %>% 
   .[month(time) == 12, year := year + 1] %>%  # december counts to the next year
   .[, .(hgt = mean(hgt), n = .N), by = .(dataset, lev, lat, lon, year, season(time))] %>% 
   .[n == 3] %>%  # keep only full seasons
   .[, n := NULL] %>% 
   .[]


# datos <- rbind(datos, ipsl, use.names = TRUE)

modern <- range(datos[dataset == "era", year])
# Surface mask
pres <- ReadNetCDF(here("DATA", "NCEP Reanalysis", "pres.mon.mean.nc"), 
                   subset = list(lat = -90:0))
pres.mean <- pres[, .(pres = median(pres)), by = lat]
pres.mean <- rbind(data.table(lat = 0.0, pres = Inf), 
                   pres.mean, 
                   data.table(lat = -90.0, pres = Inf))

censor_ground <- function(df, col = "underground") {
   df[, c(col) := lev > pres.mean[lat == .BY$lat, pres] , by = lat][]
}

surface <- function(lats = c(-90:0)) {
   geom_polygon(data = pres.mean[lat %between% range(lats)], aes(y = pres), fill = "white", 
                alpha = 0.9, color = "gray10", size = 0.5)
}


labs_part <- c(R = "Real", I = "Imaginary", M = "Module")

params <- list(season = "SON")
```



```{r calcula-ceof}
# Sacado de James
H <- 6.4*1000
lats.eof <- c(-80, -20)

year_range <- with(datos, common_range(year, dataset))

ceof_junto <- datos %>% 
   .[year %between% year_range] %>%
   .[, list(ceof = list(compute_ceof(.SD, temporal = FALSE, n = 1:2))), 
     by = .(dataset, season)]

ceof_sep <- datos %>% 
   .[year %between% year_range] %>%
   .[, list(ceof = list(compute_ceof_sep(.SD, temporal = FALSE, n = 1:2))), 
     by = .(dataset, season, lev)]
# 
# long_ceof <- datos %>% 
#    .[dataset == "era20" & season == params$season] %>% 
#    compute_ceof(temporal = FALSE)
```



```{r eof-espacial, fig.cap = "cEOF calculado usando la anomalía zonal. Parte real en sombreado, parte imaginaria en contornos (dataset = ERA Interim)."}
# gdata <- ceof[, ceof[[1]]$right, by = .(dataset, season)] %>% 
#    .[dataset == "era"] 
list(separado = ceof_sep[dataset == "era", ceof[[1]]$right, by = .(lev, season)],
     junto = ceof_junto[dataset == "era", ceof[[1]]$right, by = season]) %>% 
   rbindlist(use.names = TRUE, idcol = "metodo") %>%
   .[lev == 200 & PC == "PC2" & season == "SON" & metodo == "separado",
     hgt := complex(real = Im(hgt), imaginary = -Re(hgt))] %>% 
   
   .[lev == 200 & PC == "PC2" & season == "MAM" & metodo == "separado",
     hgt := complex(real = Im(hgt), imaginary = -Re(hgt))] %>% 
   
   
   .[lev == 200] %>% 
   ggperiodic::periodic(lon = c(0, 360)) %>% 
   ggplot(aes(lon, lat)) +
   geom_contour_fill(aes(z = Re(hgt)),
                     breaks = AnchorBreaks(0, 0.005, exclude = 0)) +
   geom_contour2(aes(z = Im(hgt),  linetype = factor(sign(..level..))),
                 breaks = AnchorBreaks(0, 0.005, exclude = 0)) +
   map(lat < 10) +
   scale_fill_divergent(guide = guide_colorstrip_bottom(35), 
                        breaks = AnchorBreaks(0, 0.005, exclude = 0),
                        limits = pm(0.039)) +
   scale_x_longitude() +
   scale_y_latitude() +
   scale_linetype_manual(values = c("1" = 1, "-1" = 2), labels = c("1" = "+", "-1" = "-"), 
                         guide = "none") +
   facet_nested(season ~ lev + PC + metodo,
                labeller = labeller(lev = AddSuffix(" hPa"),
                                    dataset = labs_datasets)) +
   coord_quickmap(ylim = c(NA, -20)) +
   theme(legend.title = element_blank())
```


```{r}
list(separado = ceof_sep[dataset == "era", ceof[[1]]$right, by = .(lev, season)],
     junto = ceof_junto[dataset == "era", ceof[[1]]$right, by = season]) %>% 
   rbindlist(use.names = TRUE, idcol = "metodo") %>%
   # .[lev == 50 & PC == "PC2" & metodo == "junto", 
   #   hgt := complex(real = -Im(hgt), imaginary = Re(hgt))] %>% 
   
   # .[lev == 50 & PC == "PC2" & metodo == "separado" & season == "DJF",
   #   hgt := complex(real = -Im(hgt), imaginary = Re(hgt))] %>%
   # 
   .[lev == 50 & PC == "PC2" & metodo == "separado" & season == "MAM",
     hgt := -hgt] %>%
   
   .[lev == 50 & PC == "PC2" & metodo == "separado" & season != "DJF",
     hgt := complex(real = Im(hgt), imaginary = -Re(hgt))] %>% 
   
   
   .[lev == 50] %>% 
   ggperiodic::periodic(lon = c(0, 360)) %>% 
   ggplot(aes(lon, lat)) +
   geom_contour_fill(aes(z = Re(hgt)),
                     breaks = AnchorBreaks(0, 0.005, exclude = 0)) +
   geom_contour2(aes(z = Im(hgt),  linetype = factor(sign(..level..))),
                 breaks = AnchorBreaks(0, 0.005, exclude = 0)) +
   map(lat < 10) +
   scale_fill_divergent(guide = guide_colorstrip_bottom(35), 
                        breaks = AnchorBreaks(0, 0.005, exclude = 0),
                        limits = pm(0.039)) +
   scale_x_longitude() +
   scale_y_latitude() +
   scale_linetype_manual(values = c("1" = 1, "-1" = 2), labels = c("1" = "+", "-1" = "-"), 
                         guide = "none") +
   facet_nested(season ~ lev + PC + metodo,
                labeller = labeller(lev = AddSuffix(" hPa"),
                                    dataset = labs_datasets)) +
   coord_quickmap(ylim = c(NA, -20)) +
   theme(legend.title = element_blank())

```


```{r}
left <- list(separado = ceof_sep[dataset == "era", ceof[[1]]$left, by = .(lev, season)],
             junto = ceof_junto[dataset == "era", ceof[[1]]$left, by = season][, lev := "conjunto"]) %>% 
   rbindlist(use.names = TRUE, idcol = "metodo")

left %>%
   copy() %>% 
   .[lev == 50 & PC == "PC2" & metodo == "separado" & season == "MAM",
     hgt := -hgt] %>%
   .[lev == 50 & PC == "PC2" & metodo == "separado" & season != "DJF",
     hgt := complex(real = Im(hgt), imaginary = -Re(hgt))] %>% 
   
   .[lev == 200 & PC == "PC2" & season == "SON" & metodo == "separado",
     hgt := complex(real = Im(hgt), imaginary = -Re(hgt))] %>% 
   
   .[lev == 200 & PC == "PC2" & season == "MAM" & metodo == "separado",
     hgt := complex(real = Im(hgt), imaginary = -Re(hgt))] %>% 
   
   
   sep_ReIm(hgt) %>% 
   
   # .[PC == "PC2" & part == "I" & lev == 200 & season == "MAM", hgt := -hgt] %>%
   # .[PC == "PC2" & part == "R" & lev == 50 & season == "MAM", hgt := -hgt] %>%
   # .[PC == "PC2" & part == "I" & lev == "conjunto" & season == "SON", hgt := -hgt] %>%
   # .[PC == "PC2" & part == "R" & lev == "conjunto" & season == "SON", hgt := -hgt] %>%
   ggplot(aes(year, hgt)) +
   geom_line(aes(color = lev)) +
   facet_nested(season  ~ PC + part)
```


```{r}
left %>% copy() %>% 
   .[lev == 50 & PC == "PC2" & metodo == "separado" & season == "MAM",
     hgt := -hgt] %>%
   .[lev == 50 & PC == "PC2" & metodo == "separado" & season != "DJF",
     hgt := complex(real = Im(hgt), imaginary = -Re(hgt))] %>% 
   
   .[lev == 200 & PC == "PC2" & season == "SON" & metodo == "separado",
     hgt := complex(real = Im(hgt), imaginary = -Re(hgt))] %>% 
   
   .[lev == 200 & PC == "PC2" & season == "MAM" & metodo == "separado",
     hgt := complex(real = Im(hgt), imaginary = -Re(hgt))] %>% 
   
   
   sep_ReIm(hgt) %>% 
   # 
   # copy() %>% 
   # .[PC == "PC2" & part == "I" & lev == 200 & season == "MAM", hgt := -hgt] %>%
   # .[PC == "PC2" & part == "R" & lev == 50 & season == "MAM", hgt := -hgt] %>%
   # .[PC == "PC2" & part == "I" & lev == "conjunto" & season == "SON", hgt := -hgt] %>%
   # .[PC == "PC2" & part == "R" & lev == "conjunto" & season == "SON", hgt := -hgt] %>%
   .[, widyr::pairwise_cor(.SD, lev, year, hgt, upper = FALSE), by = .(season, PC, part)] %>% 
   ggplot(aes(item1, item2)) +
   geom_raster(aes(fill = correlation)) +
   geom_text(aes(label = signif(correlation, 2))) +
   # scale_fill_viridis_c() +
   scale_fill_divergent() +
   facet_nested(season  ~ PC + part)
```

