---
author: "Elio Campitelli"
output: 
   # pdf_document:
   #    latex_engine: xelatex
   powerpoint_presentation:
   # ioslides_presentation:
      fig_height: 7.6
      fig_width: 12.8   
      reference_doc: template.pptx
urlcolor: blue
header_includes:
   - \usepackage[utf8]{inputenc}
params:
   season: "SON"
   PC: 2
---

---
title: `r paste0(params$season, params$PC)`
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

library(metR)
library(data.table)
library(ggplot2)
library(magrittr)
library(patchwork)
library(here)
library(ggh4x)

here <- here::here


source(here("scripts", "facet_nested.R"))
source(here("scripts", "helperfun.R"))
source(here("scripts", "data_locations.R"))
knitr_set_timer()
knitr_set_cache(cache.extra  = list(params, 50))
```

```{r}
mean_season <- function(data) {
   data %>% 
      .[is.full_season(time)] %>%  
      .[, lapply(.SD, mean), by = .(lon, lat, time = seasonaly(time))]   
}

```

```{r}
dates  <- seq(as.Date("1979-01-01"), as.Date("2019-11-01"), by = "1 month")
dates <- as.list(dates[season(dates) == params$season])
```


```{r}
datos <- ReadNetCDF(ERA5(), vars = c(hgt = "z", "u", "v", vort = "vo", air = "t"),
                    subset = list(lat = c(-90:10))) %>% 
   na.omit() %>% 
   normalise_coords() %>% 
   .[, mean_season(.SD), by = lev] %>% 
   .[season(time) == params$season]

cmap <- ReadNetCDF(CMAP(), vars = c(pp = "precip"), 
                   subset = list(lat = -90:10)) %>% 
   normalise_coords() %>%
   mean_season() %>% 
   .[, pp_next := shift(pp, -1), by = .(lon, lat)] %>% 
   .[season(time) == params$season]

olr <- ReadNetCDF(OLR(), vars = "olr") %>% 
   normalise_coords() %>%
   mean_season() %>% 
   .[season(time) == params$season]


sst <- ReadNetCDF(ERA5("mon", "sl"), vars = "sst") %>% 
   # na.omit() %>% 
   normalise_coords() %>%
   .[, mean_season(.SD)] %>% 
   .[season(time) == params$season]


sfc_air <- ReadNetCDF(NCEP(vertical = "sfc"),
                      vars = "air", 
                      subset = list(lat = -90:10)) %>% 
   normalise_coords() %>%
   .[, mean_season(.SD)] %>% 
   .[season(time) == params$season]
```

```{r}
ks <- function(vorticity_gradient, u, lat) {
   vorticity_gradient/u*(metR:::a*cos(lat*pi/180))^2
}

sqrti <- function(x) {
   sqrt(abs(x))*sign(x)
}


datos[, vort.dlat := Derivate(vort ~ lon + lat, cyclical = TRUE, sphere = TRUE)[[2]], 
      by = .(time, lev)] %>% 
   .[, U := mean(u), by = .(lat, lon, lev, season(time))] %>% 
   .[, ks := sqrti(ks(vort.dlat + f.dy(lat), U, lat))] %>% 
   .[, ":="(v_anom = Anomaly(v),
            u_anom = Anomaly(u)),
     by = .(lon, lat, lev, season(time))] %>%
   .[, ":="(v_star = Anomaly(v), 
            t_star = Anomaly(air)),
     by = .(lat, lev, time)] %>% 
   .[, ":="(vt_star = v_star*t_star,
            vu = v_anom*u_anom)]
datos <- datos
```


```{r}
divide_eof <- function(eof, which = c("left", "right", "sd")){
   setNames(lapply(which, function(x) eof[x]), which)
}

unnest_eof <- function(dt, col, which) {
   colstr <- deparse(substitute(col))
   cols <- colnames(dt)[!(colnames(dt) %in% colstr)]
   # browser()
   expr <- quote(
      dt[, col[[1]][[which]], by = c(cols)]
   )
   expr  <-  do.call(substitute, list(expr, 
                                      list(col = substitute(col))))
   eval(expr)
}
```


```{r}
ceofs <- datos %>% 
   .[lev %in% c(200, 50)] %>% 
   .[, season := season(time)] %>% 
   .[, .(ceof = list(compute_ceof(.SD, temporal = FALSE, n = params$PC))), by = .(season)]
```


<!-- ```{r} -->
<!-- datos_long <- regr <- ceofs %>%  -->
<!--    unnest_eof(ceof, "left") %>%  -->
<!--    .[, season := NULL] %>% -->
<!--    setnames("hgt", "EOF") %>%  -->
<!--    .[datos %>%  -->
<!--         melt(id.vars = c("lon", "lat", "lev", "time")),  -->
<!--      on = "time", allow.cartesian = TRUE] %>%  -->
<!--    sep_ReIm(EOF) -->
<!-- ``` -->




```{r}
regress_m <- memoise::memoise(function(ceof, data, variable) {
   regr_by <- c("lon", "lat", "PC", "season")
   pval_by <- c("term", "season", "PC")
   formula <- season + term ~ PC 
   if ("lev" %in% colnames(data)) {
      regr_by <- c("lev", regr_by)
      pval_by <- c("lev", pval_by)
      formula <- season + lev + term ~ PC 
   }
   
   data <- ceof %>% 
      unnest_eof(ceof, "left") %>% 
      setnames("hgt", "EOF") %>% 
      sep_ReIm(EOF, FALSE) %>% 
      data[., on = .NATURAL, allow.cartesian = TRUE]
   
   regr <- data %>% 
      .[, FitLm(get(variable), R, I, se = TRUE), by = c(regr_by)] %>% 
      rm_intercept() %>% 
      .[, term := factor(term, levels = c("R", "I"), labels = c("Real", "Imaginary"))] %>% 
      .[, p.val := Pvaluate(estimate, std.error, df, "fdr"), by = c(pval_by)] %>% 
      .[]
   
   class(regr) <- c("regression", class(regr))
   
   setattr(regr, "formula", formula)
   setattr(regr, "variable", variable)
   regr
})

regress <- function(ceof, data, variable) {
   variable <- deparse(substitute(variable))
   regress_m(ceof, data, variable)
}

plot.regression <- function(x, ..., keep = 0.015, skip = 2, map.fill = NA) {
   lats <- range(x$lat)
   lons <- range(x$lon)
   
   ggplot(ggperiodic::periodic(x, lon = c(0, 360)), aes(lon, lat)) +
      geom_contour_fill(aes(z = estimate), ...) +
      # geom_raster(aes(fill = estimate)) +
      geom_contour2(aes(z = p.val), breaks = 0.05, size = 0.4) +
      stat_subset(aes(subset = p.val < 0.05 & if (is.na(skip)) TRUE else is.cross(lon, lat, skip = skip)),
                  size = 0.1) +
      geom_map2(keep = keep, fill = map.fill) +
      scale_fill_divergent(attr(x, "variable")) +
      scale_x_longitude() +
      scale_y_latitude() +
      coord_quickmap(xlim = lons, ylim = lats) + 
      facet_nested(attr(x, "formula", TRUE), labeller = labeller(lev = LevLab))
}
```

```{r}
this_PC <- paste0("PC", params$PC)
```



```{r, fig.cap = "Regresión con OLR / SST"}
g1 <- regress(ceofs, olr, olr) %>%
   .[lat <= 10] %>% 
   plot() +
   guides(fill = "none")

g2 <- regress(ceofs, sst, sst) %>%
   .[lat <= 10] %>% 
   plot(na.fill = TRUE, map.fill = "white") +
   guides(fill = "none")

# g1 + g2   
cowplot::plot_grid(g1, g2)
```




```{r}
flux_regr <- regress(ceofs, datos[lev %in% c(100)], v_star) %>%
   .[, v_star := estimate] %>%
   .[, t_star := regress(ceofs, datos[lev %in% c(100)], t_star)$estimate] %>%
   .[, vt_star := regress(ceofs, datos[lev %in% c(100)], vt_star)$estimate] %>%
   .[, vt_mean := t_star*v_star]
```

```{r, fig.cap = "Regresión con V*T* y multiplicación de regresión de T* con regrsión con V*."}
flux_regr %>%
   melt(id.vars = c("lev", "term", "lon", "lat"), measure.vars = c("vt_star", "vt_mean")) %>% 
   # rm_singleton() %>%
   ggplot(aes(lon, lat)) +
   geom_contour_fill(aes(z = value)) +
   # geom_contour2(aes(z = vt_star, linetype = factor(-sign(..level..)))) +
   scale_x_longitude() +
   scale_y_latitude() +
   geom_map2(lat <= 2) +
   scale_fill_divergent("") +
   coord_quickmap() +
   facet_nested(variable ~ lev + term,
                labeller = labeller(lev = LevLab,
                                    variable = c(vt_star = "Regr(V*T)",
                                                 vt_mean = "Regr(V*) x\n Regr(T*)")))
```



```{r, fig.cap = "Igual que figura anterior pero para el promedio entre 75°S y 40°S."}
means <- datos %>% 
   .[lat %between% c(-75, -40) & lev == 100] %>% 
   .[, .(v_star = mean(v_star),
         t_star = mean(t_star), 
         vt_star = mean(vt_star), 
         lat = mean(lat)), by = .(lon, time, lev)]

regress(ceofs, means, v_star) %>% 
   .[, v_star := estimate] %>% 
   .[, t_star := regress(ceofs, means, t_star)$estimate] %>% 
   .[, vt_star := regress(ceofs, means, vt_star)$estimate] %>% 
   .[, vt_mean := t_star*v_star] %>% 
   .[, .(lon, term, vt_star, vt_mean)] %>%
   # .[, dif := vt_star - vt_mean] %>%
   melt(id.vars = c("lon", "term")) %>% 
   ggplot(aes(lon, value)) +
   geom_hline(yintercept = 0, size = 0.2) +
   geom_line(aes(color = variable)) +
   scale_color_brewer("", palette = "Set1", labels = c(vt_star = "Regr(V*T)",
                                                       vt_mean = "Regr(V*) x Regr(T*)")) +
   facet_nested(term~.)
```

```{r, fig.cap = "Regresión con Altura geopotential / v*T*."}
lats <- c(-85, -45)
g1 <- regress(ceofs, datos[lev %in% c(50, 100)], vt_star) %>% 
   plot(bins = 20, skip = 2) +
   # geom_hline(yintercept = lats, slinetype = 3, size = 0.5) +
   facet_nested(season + term ~ PC + lev, labeller = labeller(lev = LevLab))

g2 <- regress(ceofs, datos[lev %in% c(50, 100)], hgt) %>% 
   plot(bins = 20, skip = 2) +
   # geom_hline(yintercept = lats, slinetype = 3, size = 0.5) +
   facet_nested(season + term ~ PC + lev, labeller = labeller(lev = LevLab))

cowplot::plot_grid(g2, g1)
```

```{r, fig.cap = "Regresión con U. U climatológico en contornos negros."}
u <- datos[, .(u = mean(u)), by = .(lat, lon, lev)]
# 
# regress(ceofs, datos[lev %in% c(50, 100, 200)], u) %>% 
#    u[., on = .NATURAL] %>% 
#    plot.regression(bins = 20, skip = 2) +
#    geom_contour2(aes(z = u), bins = 5) +
#    geom_text_contour(aes(z = u, label = round(..level..)), bins = 5, rotate = FALSE, stroke = 0.2, 
#                      stroke.color = "white") 
#    facet_nested(season + term ~ PC + lev, labeller = labeller(lev = LevLab))
```


```{r fig.cap = "Regresión con V'U'. U climatológico en contornos."}
# regress(ceofs, datos[lev %in% c(50, 100, 200)], vu) %>% 
#    u[., on = .NATURAL] %>%
#    plot.regression(bins = 20, skip = 2) +
#    geom_contour2(aes(z = u), bins = 5) +
#    
#    
#    geom_text_contour(aes(z = u, label = round(..level..)), bins = 5, rotate = FALSE, stroke = 0.2,
#                      stroke.color = "white") +
#    facet_nested(season + term ~ PC + lev, labeller = labeller(lev = LevLab))
```

```{r, fig.cap = "Regresión con U media zonal. En contornos el U medio."}
mean_u <- datos %>% 
   .[, .(u = mean(u), lon = 0), by = .(lat, lev)] 
skip <- 1
datos %>% 
   .[, .(u = mean(u), lon = 0), by = .(lat, lev, time)] %>% 
   regress(ceofs, ., u) %>% 
   ggplot(aes(lat, lev))  +
   geom_contour_fill(aes(z = estimate)) +
   geom_contour2(aes(z = p.val), breaks = 0.05, size = 0.4) +
   stat_subset(aes(subset = p.val < 0.05 & if (is.na(skip)) TRUE else is.cross(lon, lev, skip = skip)),
               size = 0.1) +
   geom_contour2(aes(z = u), data = mean_u, color = "gray50", size = 0.6) +
   scale_x_longitude() +
   scale_y_level() +
   scale_fill_divergent("u") +
   facet_nested(season + term ~ PC)
```



## Temperatura


```{r, fig.cap = "Regresión con temperatura en superficie"}
regress(ceofs, sfc_air, air) %>% 
   plot()
```


```{r, fig.cap = "Detalle del anterior en Sudamérica."}
regress(ceofs, sfc_air, air) %>% 
   filter_sa() %>% 
   plot(keep = 1) +
   annotate("rect", fill = NA, color = "black", 
            xmin = -80 + 360, xmax = -55 + 360,
            ymin = -78, ymax = -60)
```


```{r, fig.cap = "Relación de EOF con temperatura media en la Península Antártica (caja en la figura anterior)."}
sfc_air[lon %between% c(-80 + 360, -55 + 360) & 
           lat %between% c(-78, -60)] %>% 
   .[, .(air = mean(air)), by = .(time)] %>% 
   .[unnest_eof(ceofs, ceof, "left"), on = "time"] %>% 
   sep_ReIm(hgt) %>% 
   ggplot(aes(air, hgt)) +
   geom_point(aes(Color =part)) +
   geom_smooth(method = "lm") + 
   scale_y_continuous("EOF") +
   facet_grid(~part)
```

```{r}
loocv <- function(variable, R, I) {
   data <- data.table(variable = variable, 
                      R = R, 
                      I = I)
   
   loocv_pred <- vapply(seq_len(nrow(data)), function(i) {
      predict( lm(variable ~ R + I, data = data[-i, ]), newdata = data[i])
   }, FUN.VALUE = 1.0)
   
   loocv_pred
}
```

## Precipitación (CMAP)


```{r}
cmap_mean <- cmap %>% 
   .[, .(pp = mean(pp)), by = .(lon, lat, season(time))]
```

```{r, fig.cap = "Regresión con precipitación en sudamérica."}
lats <- c(-38.75, -23.75)
lons <- ConvertLongitude(c(-63.75, -51.25))


regress(ceofs, filter_sa(cmap), pp) %>%
   plot(keep = 1, skip = NA) +
   facet_nested(PC + term ~ season) +
   annotate("rect", xmin = min(lons), xmax = max(lons), ymin = min(lats), ymax = max(lats),
            fill = NA, color = "black") +
   scale_fill_distiller("pp", palette = "BrBG", direction = 1, limits = pm(10), oob = scales::squish) 
```


```{r}
# gdata <- regress(ceofs, filter_sa(cmap), pp) %>% 
#    .[term == "Real"] 
# gdata %>% 
#    ggplot(aes(lon, lat)) +
#    geom_contour_fill(aes(z = r.squared)) +
#    stat_subset(aes(subset = p.val < 0.05 & if (is.na(skip)) TRUE else is.cross(lon, lat, skip = skip)),
#                size = 0.1) +
#    annotate("rect", xmin = min(lons), xmax = max(lons), ymin = min(lats), ymax = max(lats),
#             fill = NA, color = "black") +
#    geom_map2(keep = 1) +
#    scale_fill_distiller(palette = "Oranges", limits = c(0, 1), direction = 1) +
#    scale_x_longitude() +
#    scale_y_latitude() +
#    coord_quickmap(xlim = range(gdata$lon), ylim = range(gdata$lat)) + 
#    facet_nested(PC ~ season) 
```




```{r, fig.cap = "Precipitación media en LPB (caja de la figura anterior) en función de parte real e imaginaria de cada PC."}
cmap[lat %between% lats & lon %between% lons] %>% 
   .[, .(pp = mean(pp)), by = .(time)] %>% 
   .[unnest_eof(ceofs, ceof, "left"), on = .NATURAL, allow.cartesian = TRUE] %>% 
   sep_ReIm(hgt) %>% 
   ggplot(aes(pp, hgt)) +
   geom_point() +
   geom_smooth(method = "lm") +
   scale_y_continuous("EOF") +
   facet_nested(season ~ PC + part, scales = "free")
```


## Predicción de precipitación


```{r, fig.cap = "Regresión con precipitación en sudamérica."}
regress(ceofs, filter_sa(cmap), pp_next) %>%
   plot(keep = 1, skip = NA) +
   facet_nested(PC + term ~ season) +
   annotate("rect", xmin = min(lons), xmax = max(lons), ymin = min(lats), ymax = max(lats),
            fill = NA, color = "black") +
   scale_fill_distiller("pp", palette = "BrBG", direction = 1, limits = pm(10), oob = scales::squish) 
```

```{r}
cmap[lat %between% lats & lon %between% lons] %>% 
   .[, .(pp_next = mean(pp_next)), by = .(time)] %>% 
   .[unnest_eof(ceofs, ceof, "left"), on = .NATURAL, allow.cartesian = TRUE]  %>% 
   sep_ReIm(hgt) %>% 
   ggplot(aes(pp_next, hgt)) +
   geom_point() +
   geom_smooth(method = "lm") +
   scale_y_continuous(paste("EOF en ", params$season)) +
   scale_x_continuous(paste0("PP en el trimestre siguiente")) +
   facet_nested(season ~ PC + part, scales = "free")
```

```{r, fig.cap = "Series temporales de precipitación en LPB observadas (rojo) y modeladas con modelo lineal (azul). El modelo se ajustó con datos anteriores a 2000. Se muestra la correlación entre las series para los datos posteriores a 2000."}
M <- cmap[lat %between% lats & lon %between% lons] %>% 
   .[,  mean(pp)] 
cmap[lat %between% lats & lon %between% lons] %>% 
   .[, .(pp = mean(pp_next)), by = .(time)] %>% 
   # .[, pp := Anomaly(pp), by = .(season(time))] %>% 
   .[unnest_eof(ceofs, ceof, "left"), on = .NATURAL, allow.cartesian = TRUE] %>% 
   sep_ReIm(hgt, longer = FALSE) %>% 
   .[, model := predict(lm(pp ~ R + I, data = .SD[year(time) < 2000]), newdata = .SD), by = .(season, PC)] %>%
   melt(id.vars = c("time", "season", "PC"), measure.vars = c("pp", "model")) %>% 
   ggplot(aes(time, value)) +
   geom_vline(xintercept = lubridate::make_datetime(year = 2000), color = "gray") +
   geom_line(aes(color = variable)) +
   geom_label(data = function(x) x[year(time) >= 2000] %>% 
                 .[, widyr::pairwise_cor(.SD, variable, time, value, upper = FALSE), by = .(season, PC)],
              aes(label = scales::number(correlation, accuracy = 0.01), y = M), 
              x =  lubridate::make_datetime(year = 2010)) +
   scale_color_brewer("", palette = "Set1", label = c("Obs", "Modelo")) +
   facet_grid(season ~ PC)
```

